# Generated by Django 3.2.9 on 2022-10-25 01:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('microssatelites', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Microssatelites',
        ),
    ]
