# Generated by Django 3.2.9 on 2022-10-25 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('microssatelites', '0004_auto_20221025_1744'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='headline',
        ),
    ]
