# Generated by Django 3.2.9 on 2022-10-26 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('microssatelites', '0007_alter_user_filegbk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='fileGBK',
            field=models.BinaryField(verbose_name='File'),
        ),
    ]
