# Generated by Django 3.2.9 on 2022-10-26 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('microssatelites', '0008_alter_user_filegbk'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='fileGBK',
        ),
    ]
