# Generated by Django 3.2.9 on 2022-10-29 21:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('microssatelites', '0009_remove_user_filegbk'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cepa', models.CharField(max_length=200, verbose_name='Cepa')),
                ('motif', models.CharField(max_length=200, verbose_name='Motif')),
                ('lflanking', models.CharField(max_length=200, verbose_name='LFlanking')),
                ('rflanking', models.CharField(max_length=200, verbose_name='RFlanking')),
                ('iterations', models.IntegerField(verbose_name='Iterations')),
                ('tractlength', models.IntegerField(verbose_name='Tractlength')),
                ('consensus', models.CharField(max_length=200, verbose_name='Consensus')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='microssatelites.project')),
            ],
        ),
    ]
