# Generated by Django 3.2.9 on 2022-10-29 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('microssatelites', '0010_projectdata'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projectdata',
            old_name='cepa',
            new_name='cepa_S',
        ),
    ]
