# Generated by Django 3.2.9 on 2022-11-04 14:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('microssatelites', '0012_rename_cepa_s_projectdata_cepa'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataEstatistic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cepa', models.CharField(max_length=200, verbose_name='Cepa')),
                ('totalSSR', models.IntegerField(verbose_name='Total SSR')),
                ('totalCodificante', models.IntegerField(verbose_name='Total Codificante')),
                ('totalNaoCodificante', models.IntegerField(verbose_name='Total não Codificante')),
                ('mono', models.IntegerField(verbose_name='Mono')),
                ('di', models.IntegerField(verbose_name='Di')),
                ('tri', models.IntegerField(verbose_name='Tri')),
                ('tetra', models.IntegerField(verbose_name='Tetra')),
                ('penta', models.IntegerField(verbose_name='Penta')),
                ('hexa', models.IntegerField(verbose_name='Hexa')),
                ('totalPerfeitos', models.IntegerField(verbose_name='Total Perfeitos')),
                ('totalPerfeitosCodificantes', models.IntegerField(verbose_name='Total Perfeitos Codificantes')),
                ('totalPerfeitosNaoCodificantes', models.IntegerField(verbose_name='Toral Perfeitos Não Codificantes')),
                ('perfeitoMono', models.IntegerField(verbose_name='Perfeito Mono')),
                ('perfeitoDi', models.IntegerField(verbose_name='Perfeito Di')),
                ('perfeitoTri', models.IntegerField(verbose_name='Perfeito Tri')),
                ('perfeitoTetra', models.IntegerField(verbose_name='Perfeito Tetra')),
                ('perfeitoPenta', models.IntegerField(verbose_name='Perfeito Penta')),
                ('perfeitoHexa', models.IntegerField(verbose_name='Perfeito Hexa')),
                ('totalImperfeitos', models.IntegerField(verbose_name='Total Imperfeitos')),
                ('totalImperfeitosCodificantes', models.IntegerField(verbose_name='Total Imperfeitos Codificantes')),
                ('totalImperfeitosNaoCodificantes', models.IntegerField(verbose_name='Total Imperfeitos Não Codificantes')),
                ('imperfeitoMono', models.IntegerField(verbose_name='Imperfeito Mono')),
                ('imperfeitoDi', models.IntegerField(verbose_name='Imperfeito Di')),
                ('imperfeitoTri', models.IntegerField(verbose_name='Imperfeito Tri')),
                ('imperfeitoTetra', models.IntegerField(verbose_name='Imperfeito Tetra')),
                ('imperfeitoPenta', models.IntegerField(verbose_name='Imperfeito Penta')),
                ('imperfeitoHexa', models.IntegerField(verbose_name='Imperfeito Hexa')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='microssatelites.project')),
            ],
        ),
    ]
