# Generated by Django 3.2.9 on 2022-11-04 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('microssatelites', '0013_dataestatistic'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dataestatistic',
            old_name='cepa',
            new_name='cep',
        ),
    ]
