# Generated by Django 3.2.9 on 2022-11-04 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('microssatelites', '0014_rename_cepa_dataestatistic_cep'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dataestatistic',
            old_name='cep',
            new_name='cepa',
        ),
    ]
