# Generated by Django 3.2.9 on 2022-12-13 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('microssatelites', '0016_person'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DataEstatistic',
            new_name='DataStatistic',
        ),
    ]
