# Generated by Django 4.1.2 on 2023-02-14 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("microssatelites", "0017_rename_dataestatistic_datastatistic"),
    ]

    operations = [
        migrations.AddField(
            model_name="projectdata",
            name="pos_end",
            field=models.IntegerField(default=0, verbose_name="End"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="projectdata",
            name="pos_start",
            field=models.IntegerField(default=0, verbose_name="Start"),
            preserve_default=False,
        ),
        migrations.DeleteModel(name="Person",),
    ]
